version: "3.7"
services:
  redis:
    image: redis:latest
    ports:
      - '63790:6379'
    volumes:
      - 'expo_api_redis_data:/bitnami/redis/data'
  db:
    image: postgres
    ports:
      - "54320:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: 'expoApiDbDev,expoApiDbTest'
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - expo_api_db_data:/var/lib/postgresql/data/
volumes:
  expo_api_db_data:
  expo_api_redis_data: